# Generated by Django 5.0.6 on 2024-06-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improv_coaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvcoach',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='improvcoach',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
